### ISSUE TITLE
Suggestions for Chinese currency

### ISSUE THREAD

**Issue by asianfilm** [Chadtech/elm-money#5]
For Chinese currency, I'd suggest using "元" as the native symbol. And other changes below.

"""
cny : Currency
cny =
    { symbol = "RMB"
    , name = "Chinese Renminbi"
    , namePlural = "Chinese renminbi"
    , symbolNative = "元"
    , decimalDigits = 0
    , code = "RMB"
    }
"""

**Comment by Chadtech** [comment]
Thank you. I will look into this.

**Comment by Chadtech** [comment]
Hi @asianfilm 

Would it make sense if I changed just the native symbol? Or would changing just the native symbol alone not make sense without the other changes as well?

I did some research, and I can see that Renminbi and Yuan are the same currency, and that Renminbi is mostly used within China and Yuan is mostly used outside of China. But still when I click around online, I see the currency referenced mostly as "Chinese Yuan". So I am currently leaning towards not changing it to "Chinese Renminbi".

What do you think? You probably know more about this than I do.

**Comment by asianfilm** [comment]
Sorry, ! missed your second reply. Yes, it's fine to just change the native symbol! Although, even if keeping "yuan", I'd suggest changing the code to "RMB".

**Comment by Chadtech** [comment]
I just published `4.1.0` with the new native symbol. Thanks again!
