### ISSUE TITLE
Currency type

### ISSUE THREAD

**Issue by simonh1000** [Chadtech/elm-money#7]
I thought it was strange that code was stored as a String, meaning that while you can go Code -> Currency without a Maybe, the reverse is not true

Would be great to add information as whether the symbol is usually written before the number or after it, and with or without a space

**Comment by Chadtech** [comment]
Oh you are right. That doesnt make sense that `Code` isnt stored inside `Currency`. Let me try and fix that. This whole package is due for some re-thinking.

Also, I would love to include information like whether the symbol is on the left or right of the number. Unfortunately, thats just more complicated of a question than I have time for. Its not just a question if how a particular currency works but also how individual countries choose to display currency. number of countries x number of currencies in complexity.

**Comment by simonh1000** [comment]
Thanks so much.

For formatting, you could add the field, make educated guesses, and take PRs to fine tune?

**Comment by Chadtech** [comment]
I resolved this in the update I published today `4.0.1`. Now its _all_ custom types, and instead of record fields there are functions like `toString : Currency -> String`
